fix: arrumar login
Nocs-lab/inbcm-backend pull request #61
Opened 2024-07-03 04:49 UTC by vadolasi

2024-07-03 13:07 UTC, Everbero requested changes
Por favor resolva os problemas do code scanner @vadolasi

2024-07-03 13:18 UTC, vadolasi commented
@Everbero Os erros indicados pelo code scanner são falsos positivos. Por exemplo ele está reclamanda da falta de sanitização dos dados no middleware que faz a sanitização.

2024-07-03 15:04 UTC, Everbero approved these changes

2024-07-03 15:26 UTC, Everbero commented
@vadolasi o limiter possívelmente resolve uma parte do limite de requisições.

A sanitização tem que ser feita diretamente nos requests, por exemplo:

Para resolver a vulnerabilidade potencial na consulta ao banco de dados que depende de um valor fornecido pelo usuário, você deve assegurar que o `user_id` é validado e sanitizado corretamente antes de ser usado na consulta. Aqui estão alguns passos para melhorar a segurança do seu código:

1. **Validação do ID do Usuário**: Assegure-se de que o `user_id` é um identificador válido e esperado, como um UUID ou um ObjectId.
2. **Sanitização do Input**: Garanta que o valor de `user_id` não contenha caracteres maliciosos ou indesejados.

Aqui está uma versão melhorada do seu código que inclui validação e sanitização:

```typescript
import { Request, Response } from 'express';
import { isValidObjectId } from 'mongoose'; // Ajuste conforme a biblioteca de validação de ID que você estiver usando
import Museu from './models/Museu'; // Ajuste o caminho conforme sua estrutura de pastas

static async userMuseus(req: Request, res: Response) {
  try {
    const user_id = req.body.user.sub;

    // Validação do user_id
    if (!isValidObjectId(user_id)) {
      return res.status(400).json({ mensagem: "ID de usuário inválido." });
    }

    const museus = await Museu.find({ usuario: user_id });
    return res.status(200).json(museus);
  } catch (erro) {
    console.error("Erro ao listar museus do usuário:", erro);
    return res.status(500).json({ mensagem: "Erro ao listar museus do usuário." });
  }
}
```

### Explicação:

1. **Importação e Uso de `isValidObjectId`**:
   - Importe uma função de validação apropriada, como `isValidObjectId` do Mongoose, para validar se `user_id` é um ID de objeto válido.

2. **Validação do `user_id`**:
   - Adicione uma verificação para validar se `user_id` é um identificador válido antes de usá-lo na consulta ao banco de dados.
   - Se `user_id` não for válido, retorne uma resposta de erro 400 (Bad Request) com uma mensagem adequada.

Essa abordagem ajuda a prevenir ataques de injeção e assegura que apenas IDs válidos sejam utilizados nas consultas ao banco de dados.

2024-07-05 17:49 UTC, Everbero commented
Recusado de acordo com a resolução interna;

2024-07-05 17:49 UTC, closed without merging