Ajustar retificacao
Nocs-lab/inbcm-backend pull request #67
Opened 2024-07-12 18:52 UTC by Rickson-Rocha

Corrige retorno de  itens de uma declaração. Refatora informação de data e hora na exibição do recibo.

2024-07-12 21:20 UTC, Everbero requested changes
As datas devem passar pela função global de formatação.

2024-07-15 10:32 UTC, Rickson-Rocha commented
@Everbero  as devidas modificações já foram realizadas.

2024-07-15 12:43 UTC, Everbero approved these changes

2024-07-15 12:43 UTC, Everbero approved these changes

2024-07-15 12:46 UTC, Everbero approved these changes

2024-07-15 12:47 UTC, Everbero approved these changes

2024-07-15 13:03 UTC, Everbero approved these changes

2024-07-15 13:03 UTC, Everbero commented on service/DeclaracaoService.ts
@Rickson-Rocha avalie a possibilidade de criar apenas um método para fazer buscas, passando o tipo como um parâmetro, já que as 3 funções repetem 90% do mesmo código, por exemplo:

```javascript
async function buscarItensPorTipo(museuId, ano, userId, tipoItem) {
  try {
    // Verificar se o museu pertence ao usuário específico
    const museu = await Museu.findOne({ _id: museuId, usuario: userId });

    if (!museu) {
      throw new Error("Museu inválido ou você não tem permissão para acessá-lo");
    }

    // Definir o modelo e os campos de projeção com base no tipo de item
    let Model;
    let projectFields;

    switch (tipoItem) {
      case 'Arquivistico':
        Model = Arquivistico;
        projectFields = {
          _id: 1,
          codigoReferencia: 1,
          titulo: 1,
          nomeProdutor: 1
        };
        break;
      case 'Bibliografico':
        Model = Bibliografico;
        projectFields = {
          _id: 1,
          numeroRegistro: 1,
          situacao: 1,
          titulo: 1,
          localProducao: 1
        };
        break;
      case 'Museologico':
        Model = Museologico;
        projectFields = {
          _id: 1,
          numeroRegistro: 1,
          situacao: 1,
          denominacao: 1,
          autor: 1
        };
        break;
      default:
        throw new Error("Tipo de item inválido");
    }

    // Primeira agregação: encontrar a maior versão
    const maxVersaoResult = await Model.aggregate([
      {
        $lookup: {
          from: "declaracoes",
          localField: "declaracao_ref",
          foreignField: "_id",
          as: "declaracoes"
        }
      },
      {
        $unwind: "$declaracoes"
      },
      {
        $match: {
          "declaracoes.museu_id": new mongoose.Types.ObjectId(museuId),
          "declaracoes.anoDeclaracao": ano,
          "declaracoes.responsavelEnvio": new mongoose.Types.ObjectId(userId)
        }
      },
      {
        $group: {
          _id: null,
          maxVersao: { $max: "$versao" }
        }
      }
    ]);

    const maxVersao = maxVersaoResult[0]?.maxVersao;

    if (maxVersao === undefined) {
      return []; // Se não houver versão encontrada, retornar array vazio
    }

    // Segunda agregação: buscar os itens do tipo especificado da maior versão encontrada
    const result = await Model.aggregate([
      {
        $lookup: {
          from: "declaracoes",
          localField: "declaracao_ref",
          foreignField: "_id",
          as: "declaracoes"
        }
      },
      {
        $unwind: "$declaracoes"
      },
      {
        $match: {
          versao: maxVersao,
          "declaracoes.museu_id": new mongoose.Types.ObjectId(museuId),
          "declaracoes.anoDeclaracao": ano,
          "declaracoes.responsavelEnvio": new mongoose.Types.ObjectId(userId),
          __t: tipoItem
        }
      },
      {
        $project: projectFields
      }
    ]);

    return result;
  } catch (error) {
    console.error(`Erro ao buscar itens ${tipoItem} com maior versão:`, error);
    throw error;
  }
}

// Exemplo de uso:
const itensArquivisticos = await buscarItensPorTipo('museuIdExemplo', '2024', 'userIdExemplo', 'Arquivistico');
const itensBibliograficos = await buscarItensPorTipo('museuIdExemplo', '2024', 'userIdExemplo', 'Bibliografico');
const itensMuseologicos = await buscarItensPorTipo('museuIdExemplo', '2024', 'userIdExemplo', 'Museologico');
```

Essa abordagem reduz a repetição de código e facilita a manutenção e a extensão do código para novos tipos de itens no futuro.

2024-07-15 13:04 UTC, Everbero requested changes
Por favor verifique os comentários e providencie feedback.

2024-07-15 17:33 UTC, Everbero approved these changes

2024-07-15 17:34 UTC, Everbero approved these changes

2024-07-15 17:35 UTC, merged