fix: cria validacao para corrigir erro ao criar declaracao já existente
Nocs-lab/inbcm-backend pull request #74
Opened 2024-07-20 21:26 UTC by brunopithon

Adicionada validação para evitar a criação de declarações duplicadas. Agora, antes de criar uma nova declaração, o sistema verifica se já existe uma declaração para o mesmo museu e ano de referência. Se uma declaração existente for encontrada, o sistema retorna um erro 406 com uma mensagem informando que a declaração já existe.

2024-07-22 19:58 UTC, Everbero requested changes
**Uso incorreto do delete:** A sintaxe delete req.params.idDeclaracao está incorreta porque req.params.idDeclaracao não existe no objeto req.params. A tentativa de deletar uma propriedade de req.params que não existe não causará um erro, mas também não tem efeito.

**Utilização de !! para verificar existência:** Usar !! para verificar a existência de um valor é redundante. A verificação de existência pode ser feita simplesmente utilizando if (declaracaoExistente).

**Erro de digitação:** A mensagem de erro contém uma palavra incorreta "refica-la", que provavelmente deveria ser "retificá-la".

2024-07-23 01:57 UTC, brunopithon commented
@Everbero, foram feitas as seguintes alterações no pull request:

Adicionado o campo booleano **ultimaDeclaracao** no modelo de declaração para identificar se a declaração é a mais recente, permitindo retornar um erro 404 caso a declaração acessada não seja a última.

No método **buscarItensPorTipo**, foram incluídos itens que estavam faltando no retorno para o front-end e o código de busca foi corrigido para considerar corretamente o ano e o responsável, garantindo que apenas os itens correspondentes sejam retornados.

Realizadas correções conforme feedback da primeira avaliação do pull request, melhorando a qualidade e funcionalidade do código.

Todas as alterações acima foram feitas juntamente com os professores.

2024-07-23 18:15 UTC, Everbero requested changes

2024-07-23 18:15 UTC, Everbero commented on src/middlewares/UploadMiddleware.ts
Utilize a tipagem adequada no middleware e remova as instâncias de console.log

2024-07-24 12:07 UTC, brunopithon commented
@Everbero, segue as correções feitas:

> Remoção de instâncias de console.log.
> Resolução do problema de save() duplicado.
> Implementação de correção de tipagem no middleware.
> Correção do bug na busca de museu na linha 210.

2024-07-24 12:08 UTC, brunopithon commented
@Everbero, segue as correções feitas:

- Remoção de instâncias de console.log.
- Resolução do problema de save() duplicado.
- Implementação de correção de tipagem no middleware.
- Correção do bug na busca de museu na linha 210.

2024-07-24 13:00 UTC, Everbero commented on src/middlewares/UploadMiddleware.ts
> +    const uploadReq = req as SubmissionRequest;
Não seria melhor algo como:
```javascript
 const { arquivistico, bibliografico, museologico } = uploadReq.files;

  if (!arquivistico && !bibliografico && !museologico) {
    return res.status(400).json({ message: 'Pelo menos um arquivo deve ser enviado.' });
  }
```

2024-07-24 13:00 UTC, Everbero commented on src/controllers/DeclaracaoController.ts
>    async criarDeclaracao(req: Request, res: Response) {
Tenho reservas quanto à este método, são 125 linhas para o método criarDeclaracao(), na lógica é implementada a verificação de declarações existentes e atualização de declarações, não seria melhor especializar cada uma dessas funcionalides? Por exemplo, métodos atualizarDeclaração, retificarDeclaração, verificarDeclaracaoExistente e assim por diante.

2024-07-24 13:08 UTC, Everbero requested changes
Por favor adicionem seus comentários

2024-07-24 13:08 UTC, Everbero commented on src/controllers/DeclaracaoController.ts
>    async criarDeclaracao(req: Request, res: Response) {
Veja este exemplo

```typescript

class DeclaracaoService {
  async verificarDeclaracaoExistente(museu_id: string, anoDeclaracao: string) {
    return await Declaracoes.findOne({ museu_id, anoDeclaracao }).sort({ versao: -1 }).exec();
  }

  async updateDeclaracao(files: Express.Multer.File[], novaDeclaracao: any, tipo: string, declaracaoExistente: any, versao: number) {
    // Implementação do updateDeclaracao
  }

  criarDadosDeclaracao(
    museu: any,
    user_id: string,
    anoDeclaracao: string,
    declaracaoExistente: any,
    novaVersao: number,
    salt: string
  ) {
    return declaracaoExistente
      ? {
          museu_id: declaracaoExistente.museu_id,
          museu_nome: declaracaoExistente.museu_nome,
          anoDeclaracao: declaracaoExistente.anoDeclaracao,
          responsavelEnvio: declaracaoExistente.responsavelEnvio,
          totalItensDeclarados: declaracaoExistente.totalItensDeclarados,
          status: declaracaoExistente.status,
          retificacao: true,
          retificacaoRef: declaracaoExistente._id as mongoose.Types.ObjectId,
          versao: novaVersao,
          hashDeclaracao: createHash(declaracaoExistente._id as mongoose.Types.ObjectId, salt),
        }
      : {
          anoDeclaracao,
          museu_id: museu._id as unknown as mongoose.Types.ObjectId,
          museu_nome: museu.nome,
          responsavelEnvio: user_id as unknown as mongoose.Types.ObjectId,
          retificacao: false,
          versao: novaVersao,
          hashDeclaracao: createHash(new mongoose.Types.ObjectId(), salt),
        };
  }
}

class DeclaracaoController {
  private declaracaoService: DeclaracaoService;

  constructor() {
    this.declaracaoService = new DeclaracaoService();
  }

  async criarDeclaracao(req: Request, res: Response) {
    try {
      const { anoDeclaracao, museu: museu_id, idDeclaracao } = req.params;
      const user_id = req.user.id;

      const museu = await Museu.findOne({ _id: museu_id, usuario: user_id });
      if (!museu) {
        return res.status(400).json({ success: false, message: "Museu inválido" });
      }

      const files = req.files as { [fieldname: string]: Express.Multer.File[] };
      const salt = generateSalt();

      const declaracaoExistente = idDeclaracao
        ? await Declaracoes.findOne({
            _id: idDeclaracao,
            responsavelEnvio: user_id,
            anoDeclaracao,
            museu_id,
          }).exec()
        : await this.declaracaoService.verificarDeclaracaoExistente(museu_id, anoDeclaracao);

      if (idDeclaracao && !declaracaoExistente) {
        return res.status(404).json({ message: "Não foi encontrada uma declaração anterior para retificar." });
      }

      const ultimaDeclaracao = await Declaracoes.findOne({ museu_id, anoDeclaracao }).sort({ versao: -1 }).exec();
      const novaVersao = (ultimaDeclaracao?.versao || 0) + 1;

      const novaDeclaracaoData = this.declaracaoService.criarDadosDeclaracao(
        museu,
        user_id,
        anoDeclaracao,
        declaracaoExistente,
        novaVersao,
        salt
      );

      const novaDeclaracao = new Declaracoes(novaDeclaracaoData);

      await this.declaracaoService.updateDeclaracao(files["arquivistico"], novaDeclaracao, "arquivistico", declaracaoExistente?.arquivistico || null, novaVersao);
      await this.declaracaoService.updateDeclaracao(files["bibliografico"], novaDeclaracao, "bibliografico", declaracaoExistente?.bibliografico || null, novaVersao);
      await this.declaracaoService.updateDeclaracao(files["museologico"], novaDeclaracao, "museologico", declaracaoExistente?.museologico || null, novaVersao);

      novaDeclaracao.ultimaDeclaracao = true;
      await novaDeclaracao.save();

      await Declaracoes.updateMany({ museu_id, anoDeclaracao, _id: { $ne: novaDeclaracao._id } }, { ultimaDeclaracao: false });

      return res.status(200).json(novaDeclaracao);
    } catch (error) {
      return res.status(500).json({ message: "Erro ao enviar uma declaração: ", error });
    }
  }
}

export default new DeclaracaoController();
```

Mudanças realizadas:
1. Consolidamos a verificação da existência de uma declaração anterior em uma única variável `declaracaoExistente`, independentemente de ser uma nova declaração ou retificação.
2. Simplificamos a criação dos dados da declaração utilizando uma única função `criarDadosDeclaracao` que decide quais dados preencher com base na presença de uma declaração existente.
3. Reduzimos o uso de condicionais `if else` para melhorar a legibilidade do código.

2024-07-24 13:51 UTC, brunopithon commented on src/controllers/DeclaracaoController.ts
>    async criarDeclaracao(req: Request, res: Response) {
@Everbero, estamos cientes das alterações necessárias e já discutimos a refatoração deste método, incluindo sua transferência do controller para o service. Esse ajuste está no nosso radar. É crucial que esta versão seja mesclada agora, pois essas mudanças iram precisar de tempo, vamos precisar realizar uma bateria de testes devido ao volume significativo de mudanças

2024-07-24 13:57 UTC, brunopithon commented
@Everbero, feitas todas as alterações no middleware de upload.

2024-07-24 14:17 UTC, Everbero commented
Deve ser refatorado seguindo as instruções da issue #75

2024-07-24 18:59 UTC, Rickson-Rocha commented
@Everbero  fiz alterações nos métodos de criar declaração (controller)  e criarDadosDeclaracao ( no service). É válido salientar que tais alterações ainda não atendem 100% a especificações listadas na issue #75.  Inclusive,quando se trata de testes unitários,visto que essa é uma atividade ligada à  próxima sprint. Reforço que as  novas funcionalidades e correções implementadas nessa branch são de suma importância para consolidação do módulo declarante.

2024-07-24 19:39 UTC, Everbero approved these changes

2024-07-24 19:40 UTC, merged